# Generated by Django 5.2 on 2026-02-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('field_name', models.CharField(blank=True, default='', max_length=128)),
                ('error_message', models.TextField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importer.importjob')),
            ],
            options={
                'db_table': 'import_errors',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='import_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['created_by'], name='import_job_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='importerror',
            index=models.Index(fields=['import_job', 'row_number'], name='import_error_row_idx'),
        ),
    ]
