# Generated by Django 5.2.10 on 2026-01-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0002_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_no",
                    models.CharField(max_length=20, unique=True, verbose_name="工号"),
                ),
                ("hire_date", models.DateField(verbose_name="入职日期")),
                (
                    "salary_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="月度基本工资",
                        max_digits=10,
                        verbose_name="基本工资",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待入职"),
                            ("active", "在职"),
                            ("resigned", "已离职"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "resigned_date",
                    models.DateField(blank=True, null=True, verbose_name="离职日期"),
                ),
                (
                    "resigned_reason",
                    models.TextField(blank=True, default="", verbose_name="离职原因"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organization.department",
                        verbose_name="所属部门",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="organization.post",
                        verbose_name="岗位",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工档案",
                "verbose_name_plural": "员工档案",
                "ordering": ["-created_at"],
            },
        ),
    ]
