# Generated by Django 6.0.1 on 2026-02-04 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_historicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('hot', '热门推荐'), ('new', '新品推荐'), ('personalized', '个性化推荐'), ('category', '分类推荐')], default='hot', max_length=20, verbose_name='规则类型')),
                ('description', models.TextField(blank=True, default='', verbose_name='规则描述')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置参数')),
                ('priority', models.IntegerField(db_index=True, default=0, verbose_name='优先级')),
                ('limit', models.IntegerField(default=10, verbose_name='限制数量')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐规则',
                'verbose_name_plural': '推荐规则管理',
                'db_table': 'recommendation_rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product', verbose_name='商品')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='recommendations.recommendationrule', verbose_name='推荐规则')),
            ],
            options={
                'verbose_name': '推荐商品',
                'verbose_name_plural': '推荐商品管理',
                'db_table': 'recommended_products',
                'ordering': ['-sort_order', '-created_at'],
                'unique_together': {('rule', 'product')},
            },
        ),
    ]
