# Generated by Django 5.2 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('national', 'National'), ('provincial', 'Provincial'), ('city_county', 'City/County')], db_index=True, max_length=32)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('protection_unit', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heritage_items', to='categories.category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heritage_items', to='regions.region')),
            ],
            options={
                'db_table': 'heritage_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='heritage_name_idx'), models.Index(fields=['category'], name='heritage_category_idx'), models.Index(fields=['region'], name='heritage_region_idx')],
            },
        ),
    ]
