# Generated by Django 5.2.10 on 2026-01-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类的显示名称，如"川菜"、"早餐"等', max_length=50, verbose_name='分类名称')),
                ('type', models.CharField(choices=[('cuisine', '菜系'), ('scene', '场景'), ('crowd', '人群'), ('difficulty', '难度'), ('taste', '口味')], db_index=True, help_text='分类类型：菜系/场景/人群/口味', max_length=20, verbose_name='分类类型')),
                ('sort_order', models.IntegerField(default=0, help_text='数值越小越靠前，默认为0', verbose_name='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
                'ordering': ['type', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['type'], name='categories_type_735b1a_idx'), models.Index(fields=['sort_order'], name='categories_sort_or_77e69f_idx')],
                'unique_together': {('type', 'name')},
            },
        ),
    ]
