# Generated by Django 5.2.10 on 2026-01-30 01:13

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    创建初始分类数据

    包含：
    - 八大菜系
    - 常见场景（早餐、午餐、晚餐等）
    - 适用人群（儿童、老人、孕妇等）
    - 口味类型（辣、甜、酸等）
    """
    Category = apps.get_model('categories', 'Category')

    # 八大菜系
    cuisines = [
        {'name': '川菜', 'type': 'cuisine', 'sort_order': 1},
        {'name': '粤菜', 'type': 'cuisine', 'sort_order': 2},
        {'name': '鲁菜', 'type': 'cuisine', 'sort_order': 3},
        {'name': '苏菜', 'type': 'cuisine', 'sort_order': 4},
        {'name': '浙菜', 'type': 'cuisine', 'sort_order': 5},
        {'name': '湘菜', 'type': 'cuisine', 'sort_order': 6},
        {'name': '徽菜', 'type': 'cuisine', 'sort_order': 7},
        {'name': '闽菜', 'type': 'cuisine', 'sort_order': 8},
    ]

    # 常见场景
    scenes = [
        {'name': '早餐', 'type': 'scene', 'sort_order': 1},
        {'name': '午餐', 'type': 'scene', 'sort_order': 2},
        {'name': '晚餐', 'type': 'scene', 'sort_order': 3},
        {'name': '下午茶', 'type': 'scene', 'sort_order': 4},
        {'name': '夜宵', 'type': 'scene', 'sort_order': 5},
        {'name': '快手菜', 'type': 'scene', 'sort_order': 6},
        {'name': '宴客菜', 'type': 'scene', 'sort_order': 7},
    ]

    # 适用人群
    crowds = [
        {'name': '儿童', 'type': 'crowd', 'sort_order': 1},
        {'name': '老人', 'type': 'crowd', 'sort_order': 2},
        {'name': '孕妇', 'type': 'crowd', 'sort_order': 3},
        {'name': '健身人群', 'type': 'crowd', 'sort_order': 4},
        {'name': '素食者', 'type': 'crowd', 'sort_order': 5},
    ]

    # 口味类型
    tastes = [
        {'name': '辣', 'type': 'taste', 'sort_order': 1},
        {'name': '甜', 'type': 'taste', 'sort_order': 2},
        {'name': '酸', 'type': 'taste', 'sort_order': 3},
        {'name': '咸', 'type': 'taste', 'sort_order': 4},
        {'name': '鲜', 'type': 'taste', 'sort_order': 5},
        {'name': '清淡', 'type': 'taste', 'sort_order': 6},
        {'name': '麻', 'type': 'taste', 'sort_order': 7},
    ]

    # 合并所有分类
    all_categories = cuisines + scenes + crowds + tastes

    # 批量创建
    for category_data in all_categories:
        Category.objects.create(**category_data)


def remove_initial_categories(apps, schema_editor):
    """删除初始分类数据（用于回滚）"""
    Category = apps.get_model('categories', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
