# Generated by Django 6.0.2 on 2026-02-05 02:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('product_image', models.URLField(blank=True, default='', verbose_name='商品图片')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='浏览时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '浏览历史',
                'verbose_name_plural': '浏览历史管理',
                'db_table': 'browsing_history',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='browsing_hi_user_id_4bf1b8_idx'), models.Index(fields=['user', 'product_id'], name='browsing_hi_user_id_b64654_idx')],
            },
        ),
    ]
