# Generated by Django 5.2.10 on 2026-01-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：早班/中班/晚班/全天", max_length=20, verbose_name="班次名称"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="上班开始时间")),
                ("end_time", models.TimeField(verbose_name="下班结束时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "班次定义",
                "verbose_name_plural": "班次定义",
                "db_table": "shifts",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_index=True, verbose_name="排班日期")),
                (
                    "is_swapped",
                    models.BooleanField(default=False, verbose_name="是否已调班"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="employees.employeeprofile",
                        verbose_name="员工",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="schedules.shift",
                        verbose_name="班次",
                    ),
                ),
            ],
            options={
                "verbose_name": "排班计划",
                "verbose_name_plural": "排班计划",
                "db_table": "schedules",
                "ordering": ["-work_date", "shift__start_time"],
                "unique_together": {("employee", "work_date")},
            },
        ),
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField(verbose_name="期望调整日期")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="申请原因"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审批"),
                            ("APPROVED", "已批准"),
                            ("REJECTED", "已拒绝"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "approval_remark",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_swap_requests",
                        to="employees.employeeprofile",
                        verbose_name="审批管理员",
                    ),
                ),
                (
                    "original_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="schedules.schedule",
                        verbose_name="原定排班",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="employees.employeeprofile",
                        verbose_name="发起员工",
                    ),
                ),
                (
                    "target_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_swap_requests",
                        to="schedules.shift",
                        verbose_name="期望调整班次",
                    ),
                ),
            ],
            options={
                "verbose_name": "调班申请",
                "verbose_name_plural": "调班申请",
                "db_table": "shift_swap_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
