# Generated by Django 5.2.10 on 2026-02-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="energy name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("WATER", "Water"),
                            ("ELECTRICITY", "Electricity"),
                            ("GAS", "Gas"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="energy code",
                    ),
                ),
                ("unit", models.CharField(max_length=32, verbose_name="unit")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="icon"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "energy type",
                "verbose_name_plural": "energy types",
                "db_table": "em_energy_types",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="device id"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="device name")),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="device model",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("FAULT", "Fault"),
                        ],
                        default="OFFLINE",
                        max_length=16,
                        verbose_name="device status",
                    ),
                ),
                (
                    "last_data_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last data time"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="buildings.room",
                        verbose_name="room",
                    ),
                ),
                (
                    "energy_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="devices.energytype",
                        verbose_name="energy type",
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "db_table": "em_devices",
                "indexes": [
                    models.Index(
                        fields=["energy_type"], name="idx_em_devices_energy_type_id"
                    ),
                    models.Index(fields=["room"], name="idx_em_devices_room_id"),
                    models.Index(fields=["status"], name="idx_em_devices_status"),
                ],
            },
        ),
    ]
