# Generated by Django 6.0.1 on 2026-02-04 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_historicalproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='用户ID')),
                ('order_item_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='订单项ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=5, verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='评价图片')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名评价')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'order_item_id')},
            },
        ),
    ]
