# Generated by Django 5.2.10 on 2026-01-29 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBehaviorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "behavior_type",
                    models.CharField(
                        db_index=True,
                        help_text="用户行为的类型，如 login/search/view/collect 等",
                        max_length=20,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="行为的目标对象，如菜谱 ID 或页面路径",
                        max_length=500,
                        null=True,
                        verbose_name="行为目标",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="行为发生的时间",
                        verbose_name="行为时间",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="额外的行为相关数据，如搜索关键词、停留时长等，JSON 格式",
                        null=True,
                        verbose_name="额外数据",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="用户发起行为时的 IP 地址",
                        null=True,
                        verbose_name="IP 地址",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="用户发起行为时的浏览器 User-Agent",
                        null=True,
                        verbose_name="用户代理",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="执行行为的用户，为空表示未登录用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为日志",
                "verbose_name_plural": "用户行为日志",
                "db_table": "user_behavior_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="behavior_user_time_idx"
                    ),
                    models.Index(
                        fields=["behavior_type", "-timestamp"],
                        name="behavior_type_time_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="behavior_time_idx"),
                ],
            },
        ),
    ]
