# Generated by Django 6.0.1 on 2026-01-28 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('clock_in_location', models.CharField(blank=True, max_length=200, verbose_name='签到地点')),
                ('clock_out_time', models.DateTimeField(blank=True, null=True, verbose_name='签退时间')),
                ('clock_out_location', models.CharField(blank=True, max_length=200, verbose_name='签退地点')),
                ('status', models.CharField(choices=[('NORMAL', '正常'), ('LATE', '迟到'), ('EARLY_LEAVE', '早退'), ('MISSING', '缺卡'), ('ABNORMAL', '异常')], default='NORMAL', max_length=20, verbose_name='考勤状态')),
                ('correction_remark', models.TextField(blank=True, verbose_name='更正备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employeeprofile', verbose_name='员工')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='schedules.schedule', verbose_name='排班')),
            ],
            options={
                'verbose_name': '考勤记录',
                'verbose_name_plural': '考勤记录',
                'db_table': 'attendance_records',
                'ordering': ['-clock_in_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('employee', 'schedule'), name='unique_employee_schedule_attendance')],
            },
        ),
    ]
