# Generated by Django 5.2.10 on 2026-01-29 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_records DROP COLUMN overtime_hours;",
            reverse_sql="ALTER TABLE attendance_records ADD COLUMN overtime_hours DECIMAL(5,2) NOT NULL DEFAULT 0.00;"
        ),
    ]
