# Generated by Django 5.2.11 on 2026-02-24 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='value')),
                ('voltage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='voltage')),
                ('current', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='current')),
                ('power', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='power')),
                ('flow_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='flow rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_data', to='devices.device', verbose_name='device')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_data', to='devices.energytype', verbose_name='energy type')),
            ],
            options={
                'verbose_name': 'energy data',
                'verbose_name_plural': 'energy data',
                'db_table': 'em_energy_data',
                'indexes': [models.Index(fields=['timestamp'], name='idx_energy_data_ts'), models.Index(fields=['device', 'timestamp'], name='idx_energy_data_dev_ts'), models.Index(fields=['energy_type', 'timestamp'], name='idx_energy_data_type_ts')],
                'constraints': [models.UniqueConstraint(fields=('device', 'energy_type', 'timestamp'), name='uk_energy_data_dev_type_ts')],
            },
        ),
        migrations.CreateModel(
            name='EnergyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=16, verbose_name='period type')),
                ('period_date', models.DateField(verbose_name='period date')),
                ('total_value', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='total value')),
                ('peak_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='peak value')),
                ('peak_time', models.DateTimeField(blank=True, null=True, verbose_name='peak time')),
                ('avg_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='avg value')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_statistics', to='devices.device', verbose_name='device')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_statistics', to='devices.energytype', verbose_name='energy type')),
            ],
            options={
                'verbose_name': 'energy statistic',
                'verbose_name_plural': 'energy statistics',
                'db_table': 'em_energy_statistics',
                'indexes': [models.Index(fields=['period_date'], name='idx_energy_stats_period_date'), models.Index(fields=['period_type', 'period_date'], name='idx_energy_stats_type_date')],
                'constraints': [models.UniqueConstraint(fields=('device', 'energy_type', 'period_type', 'period_date'), name='uk_energy_stats_unique_period')],
            },
        ),
    ]
