# Generated by Django 5.2.11 on 2026-02-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('feedback_type', models.CharField(choices=[('feature', '功能建议'), ('bug', 'Bug反馈'), ('other', '其他')], default='other', max_length=20, verbose_name='反馈类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已完成'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '反馈建议',
                'verbose_name_plural': '反馈建议列表',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
