# Generated by Django 5.2.10 on 2026-02-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="校区名称")),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="校区编码"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="校区容量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "校区",
                "verbose_name_plural": "校区",
                "db_table": "em_campuses",
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="建筑名称")),
                (
                    "code",
                    models.CharField(max_length=64, unique=True, verbose_name="建筑编码"),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("TEACHING", "教学区"),
                            ("LIVING", "生活区"),
                            ("OFFICE", "办公区"),
                        ],
                        default="TEACHING",
                        max_length=16,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="地址"
                    ),
                ),
                (
                    "floors_count",
                    models.PositiveIntegerField(default=0, verbose_name="楼层数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="buildings.campus",
                        verbose_name="所属校区",
                    ),
                ),
            ],
            options={
                "verbose_name": "建筑",
                "verbose_name_plural": "建筑",
                "db_table": "em_buildings",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.IntegerField(verbose_name="楼层号")),
                ("name", models.CharField(max_length=64, verbose_name="楼层名称")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="buildings.building",
                        verbose_name="所属建筑",
                    ),
                ),
            ],
            options={
                "verbose_name": "楼层",
                "verbose_name_plural": "楼层",
                "db_table": "em_floors",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=32, verbose_name="房间号")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("DORMITORY", "宿舍"),
                            ("OFFICE", "办公室"),
                            ("CLASSROOM", "教室"),
                        ],
                        default="CLASSROOM",
                        max_length=16,
                        verbose_name="房间类型",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="面积(㎡)",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="所属部门"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="buildings.floor",
                        verbose_name="所属楼层",
                    ),
                ),
            ],
            options={
                "verbose_name": "房间",
                "verbose_name_plural": "房间",
                "db_table": "em_rooms",
            },
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.UniqueConstraint(
                fields=("campus", "name"), name="uk_em_buildings_campus_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="floor",
            constraint=models.UniqueConstraint(
                fields=("building", "floor_number"),
                name="uk_em_floors_building_floor_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("floor", "room_number"), name="uk_em_rooms_floor_room_number"
            ),
        ),
    ]
