# Generated by Django 5.2.11 on 2026-02-13 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_attraction_attractions_categor_fb455a_idx_and_more'),
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['attraction', 'status', 'is_deleted'], name='comments_attract_372968_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'attraction', 'status'], name='comments_user_id_64d11d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status', 'is_deleted'], name='comments_status_96ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'attraction'], name='favorites_user_id_af38bf_idx'),
        ),
    ]
