# Generated by Django 5.2.10 on 2026-02-14 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0003_attraction_attractions_categor_fb455a_idx_and_more"),
        ("comments", "0002_comment_comments_attract_372968_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["user", "is_deleted", "-created_at"],
                name="comments_user_id_a39036_idx",
            ),
        ),
    ]
