# Generated by Django 5.2.10 on 2026-02-08 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="配置键"),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("crawler", "爬虫配置"),
                            ("system", "系统配置"),
                            ("api", "API配置"),
                        ],
                        default="crawler",
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_configs",
                "ordering": ["config_type", "key"],
                "indexes": [
                    models.Index(fields=["key"], name="system_conf_key_4990ef_idx"),
                    models.Index(
                        fields=["config_type"], name="system_conf_config__b00bc2_idx"
                    ),
                ],
            },
        ),
    ]
