# Generated by Django 6.0.1 on 2026-01-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('ATTENDANCE', '考勤申诉'), ('SALARY', '薪资申诉')], max_length=20, verbose_name='申诉类型')),
                ('target_id', models.IntegerField(help_text='考勤记录ID或薪资记录ID', verbose_name='目标记录ID')),
                ('reason', models.TextField(verbose_name='申诉原因')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='审批状态')),
                ('approval_remark', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appeals', to='employees.employeeprofile', verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='employees.employeeprofile', verbose_name='申诉员工')),
            ],
            options={
                'verbose_name': '异常申诉',
                'verbose_name_plural': '异常申诉',
                'db_table': 'appeals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='appeals_employe_3cfe21_idx'), models.Index(fields=['appeal_type', 'status'], name='appeals_appeal__5ff110_idx'), models.Index(fields=['target_id'], name='appeals_target__a402aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='格式: YYYY-MM', max_length=7, verbose_name='年月')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基本工资')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='岗位津贴')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='加班费')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='扣款')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实发工资')),
                ('work_days', models.IntegerField(default=0, verbose_name='出勤天数')),
                ('late_count', models.IntegerField(default=0, verbose_name='迟到次数')),
                ('missing_count', models.IntegerField(default=0, verbose_name='缺卡次数')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='加班时长(小时)')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '已发布'), ('APPEALED', '申诉中'), ('ADJUSTED', '已调整')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employeeprofile', verbose_name='员工')),
            ],
            options={
                'verbose_name': '薪资记录',
                'verbose_name_plural': '薪资记录',
                'db_table': 'salary_records',
                'ordering': ['-year_month', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'year_month'], name='salary_reco_employe_8a9ded_idx'), models.Index(fields=['year_month'], name='salary_reco_year_mo_647a53_idx'), models.Index(fields=['status'], name='salary_reco_status_33ad2b_idx')],
                'unique_together': {('employee', 'year_month')},
            },
        ),
    ]
