# Generated by Django 5.2.10 on 2026-02-04 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(default=0, verbose_name="商品总数"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="商品总金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "购物车",
                "verbose_name_plural": "购物车管理",
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="商品名称")),
                (
                    "product_image",
                    models.URLField(blank=True, default="", verbose_name="商品图片"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品单价"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="数量")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="小计金额"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="添加时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "购物车商品",
                "verbose_name_plural": "购物车商品管理",
                "db_table": "cart_items",
                "ordering": ["-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="订单号"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=50, verbose_name="收货人姓名"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=11, verbose_name="收货人手机号"),
                ),
                (
                    "recipient_province",
                    models.CharField(default="", max_length=50, verbose_name="省份"),
                ),
                (
                    "recipient_city",
                    models.CharField(default="", max_length=50, verbose_name="城市"),
                ),
                (
                    "recipient_district",
                    models.CharField(default="", max_length=50, verbose_name="区县"),
                ),
                (
                    "recipient_address",
                    models.CharField(max_length=255, verbose_name="详细地址"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="订单总额"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="运费"
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="实付金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待付款"),
                            ("pending_shipment", "待发货"),
                            ("shipped", "已发货"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "express_company",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="物流公司"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="物流单号"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="订单备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="付款时间"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发货时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单管理",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255, verbose_name="商品名称")),
                (
                    "product_image",
                    models.URLField(blank=True, default="", verbose_name="商品图片"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="购买单价"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="购买数量"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="小计金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "订单商品",
                "verbose_name_plural": "订单商品管理",
                "db_table": "order_items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("return", "退货"), ("exchange", "换货")],
                        default="return",
                        max_length=20,
                        verbose_name="申请类型",
                    ),
                ),
                ("reason", models.TextField(verbose_name="退换货原因")),
                (
                    "evidence_images",
                    models.JSONField(blank=True, null=True, verbose_name="凭证图片URL列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已同意"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, default="", verbose_name="处理意见"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="申请时间",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
            ],
            options={
                "verbose_name": "退换货申请",
                "verbose_name_plural": "退换货管理",
                "db_table": "return_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
