# Generated by Django 5.2.10 on 2026-01-24 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="格式: YYYY-MM", max_length=7, verbose_name="薪资月份"
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本工资"
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=6, verbose_name="加班小时数"
                    ),
                ),
                (
                    "overtime_pay",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="加班费"
                    ),
                ),
                ("late_count", models.IntegerField(default=0, verbose_name="迟到次数")),
                ("early_count", models.IntegerField(default=0, verbose_name="早退次数")),
                (
                    "attendance_deduction",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="考勤扣款"
                    ),
                ),
                (
                    "final_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="实发工资"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资记录",
                "verbose_name_plural": "薪资记录",
                "db_table": "salary_salaryrecord",
                "ordering": ["-month", "-created_at"],
                "unique_together": {("user", "month")},
            },
        ),
    ]
