# Generated by Django 5.2.10 on 2026-01-25 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("salary_error", "薪资计算错误"),
                            ("attendance_error", "考勤数据错误"),
                            ("overtime_missing", "加班记录缺失"),
                            ("deduction_error", "扣款异常"),
                            ("employee_appeal", "员工申诉"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="异常类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="异常描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "resolution",
                    models.TextField(blank=True, default="", verbose_name="处理方案"),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="调整金额"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上报人",
                    ),
                ),
                (
                    "salary_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="salary.salaryrecord",
                        verbose_name="关联薪资记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资异常",
                "verbose_name_plural": "薪资异常处理",
                "db_table": "salary_exception",
                "ordering": ["-created_at"],
            },
        ),
    ]
