# Generated by Django 5.2.10 on 2026-01-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="考勤日期")),
                (
                    "check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="签到时间"),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="签退时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("late", "迟到"),
                            ("early", "早退"),
                            ("leave", "休假"),
                            ("absent", "缺勤"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="考勤状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "db_table": "attendance_attendance",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
