# Generated by Django 6.0.1 on 2026-01-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_checker_attendance_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checker',
        ),
    ]
