# Generated by Django 6.0.1 on 2026-02-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(db_index=True, help_text='360问答原始问题ID，用于去重和数据关联', max_length=50, unique=True, verbose_name='问题ID')),
                ('title', models.CharField(max_length=500, verbose_name='问题标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='问题描述')),
                ('category', models.CharField(blank=True, db_index=True, help_text='如：影视、烦恼、软件等（去除方括号）', max_length=50, null=True, verbose_name='分类')),
                ('publish_time', models.DateField(blank=True, db_index=True, help_text='问题发布日期，格式：YYYY.MM.DD', null=True, verbose_name='发布时间')),
                ('location', models.CharField(blank=True, db_index=True, help_text='问题发布地，如：美国、广东、浙江', max_length=100, null=True, verbose_name='地理位置')),
                ('answer_count', models.IntegerField(default=0, help_text='该问题的回答总数', verbose_name='回答数量')),
                ('crawl_page', models.IntegerField(default=1, help_text='数据来源于第几页', verbose_name='爬取页码')),
                ('source_url', models.URLField(help_text='360问答详情页URL', max_length=500, unique=True, verbose_name='来源链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'crawler_question',
                'ordering': ['-publish_time', '-created_at'],
                'indexes': [models.Index(fields=['question_id'], name='idx_question_id'), models.Index(fields=['publish_time'], name='idx_publish_time'), models.Index(fields=['category'], name='idx_category'), models.Index(fields=['location'], name='idx_location'), models.Index(fields=['-created_at'], name='idx_created_desc'), models.Index(fields=['answer_count'], name='idx_answer_count')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='答案内容')),
                ('answerer', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='回答者')),
                ('answer_time', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('source_order', models.IntegerField(default=1, help_text='用于保持答案在源页面的原始顺序', verbose_name='在源页面中的顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='crawler.question', verbose_name='问题')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
                'db_table': 'crawler_answer',
                'ordering': ['source_order'],
                'indexes': [models.Index(fields=['question'], name='idx_answer_question'), models.Index(fields=['answerer'], name='idx_answerer'), models.Index(fields=['answer_time'], name='idx_answer_time')],
                'unique_together': {('question', 'source_order')},
            },
        ),
    ]
