# Generated by Django 5.2.10 on 2026-02-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "crawler_tag",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="问题标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="问题描述"),
                ),
                ("answer_content", models.TextField(verbose_name="回答内容")),
                (
                    "answer_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="回答时间"),
                ),
                (
                    "answerer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="回答者"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(max_length=255, unique=True, verbose_name="来源链接"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="questions",
                        to="crawler.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "问答",
                "verbose_name_plural": "问答",
                "db_table": "crawler_question",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="crawler_que_title_238b59_idx"),
                    models.Index(
                        fields=["created_at"], name="crawler_que_created_f2ecce_idx"
                    ),
                    models.Index(
                        fields=["answerer"], name="crawler_que_answere_7cac67_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="crawler_que_created_f80c32_idx"
                    ),
                ],
            },
        ),
    ]
