# Generated by Django 5.2.11 on 2026-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerGenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('total', models.IntegerField(default=0, verbose_name='总问题数')),
                ('completed', models.IntegerField(default=0, verbose_name='已完成')),
                ('failed', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped', models.IntegerField(default=0, verbose_name='跳过数')),
                ('last_question_id', models.CharField(blank=True, max_length=50, verbose_name='最后处理的问题ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('paused', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '回答生成进度',
                'verbose_name_plural': '回答生成进度',
                'db_table': 'crawler_answer_generation_progress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='标识该回答是否由AI生成', verbose_name='是否AI生成'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_ai_generated'], name='idx_ai_generated'),
        ),
    ]
