# Generated by Django 5.2.10 on 2026-02-04 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="优惠券名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="优惠券描述"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("full_reduction", "满减券"), ("discount", "折扣券")],
                        default="full_reduction",
                        max_length=20,
                        verbose_name="优惠类型",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="使用门槛"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="优惠金额"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="折扣率",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="有效期开始")),
                ("valid_until", models.DateTimeField(verbose_name="有效期结束")),
                ("total_quantity", models.IntegerField(default=0, verbose_name="发放总量")),
                (
                    "per_user_limit",
                    models.IntegerField(default=1, verbose_name="每人限领数量"),
                ),
                (
                    "issued_quantity",
                    models.IntegerField(default=0, verbose_name="已发放数量"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券管理",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        db_index=True,
                        default="unused",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "obtained_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="领取时间"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="marketing.coupon",
                        verbose_name="优惠券",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券管理",
                "db_table": "user_coupons",
                "ordering": ["-obtained_at"],
            },
        ),
    ]
