# Generated by Django 5.2.10 on 2026-02-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketing", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoupon",
            name="used_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_coupons",
                to="orders.order",
                verbose_name="使用的订单",
            ),
        ),
    ]
