# Generated by Django 6.0.1 on 2026-02-05 08:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='副标题')),
                ('image', models.URLField(verbose_name='Banner 图片')),
                ('link_type', models.CharField(choices=[('none', '无链接'), ('product', '商品详情'), ('category', '分类页'), ('activity', '活动页'), ('url', '外部链接')], default='none', max_length=20, verbose_name='链接类型')),
                ('link_value', models.CharField(blank=True, default='', max_length=500, verbose_name='链接值')),
                ('position', models.CharField(choices=[('home', '首页'), ('category', '分类页'), ('product', '商品页'), ('activity', '活动页')], default='home', max_length=20, verbose_name='展示位置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Banner 轮播图',
                'verbose_name_plural': 'Banner 轮播图管理',
                'db_table': 'banners',
                'ordering': ['position', '-sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='促销活动名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='活动描述')),
                ('promotion_type', models.CharField(choices=[('flash_sale', '限时秒杀'), ('bundle', '组合优惠'), ('special_offer', '特价活动'), ('seasonal', '季节性促销')], default='special_offer', max_length=20, verbose_name='促销类型')),
                ('start_time', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(verbose_name='活动结束时间')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, help_text='例如：8.5 表示 8.5 折', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(9.9)], verbose_name='折扣率')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='直接减免的金额', max_digits=10, verbose_name='优惠金额')),
                ('image', models.URLField(blank=True, default='', verbose_name='活动图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='marketing.coupon', verbose_name='关联优惠券')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动管理',
                'db_table': 'promotions',
                'ordering': ['-sort_order', '-created_at'],
            },
        ),
    ]
