# Generated by Django 5.2.10 on 2026-02-07 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="日志ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Celery任务ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "进行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        help_text="demo: 演示模式, batch: 分批采集",
                        max_length=20,
                        verbose_name="采集模式",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[("json", "JSON API"), ("playwright", "Playwright渲染")],
                        max_length=20,
                        null=True,
                        verbose_name="采集来源",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "items_collected",
                    models.IntegerField(default=0, verbose_name="采集数量"),
                ),
                ("items_success", models.IntegerField(default=0, verbose_name="成功数量")),
                ("items_failed", models.IntegerField(default=0, verbose_name="失败数量")),
                (
                    "log_content",
                    models.TextField(blank=True, null=True, verbose_name="日志内容"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "采集日志",
                "verbose_name_plural": "采集日志",
                "db_table": "crawl_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_id"], name="crawl_logs_task_id_e039cf_idx"
                    ),
                    models.Index(
                        fields=["status"], name="crawl_logs_status_987f48_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="crawl_logs_created_483c47_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="商品ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="商品标题")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格（元）"
                    ),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="销量")),
                ("shop", models.CharField(max_length=200, verbose_name="店铺名称")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=1000, null=True, verbose_name="商品图片URL"
                    ),
                ),
                (
                    "detail_url",
                    models.URLField(max_length=1000, verbose_name="商品详情页URL"),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="品牌"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="类目"
                    ),
                ),
                ("batch_no", models.CharField(max_length=50, verbose_name="采集批次号")),
                ("crawl_time", models.DateTimeField(verbose_name="采集时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "products",
                "ordering": ["-crawl_time"],
                "indexes": [
                    models.Index(fields=["title"], name="products_title_6a4e5e_idx"),
                    models.Index(fields=["price"], name="products_price_fe467e_idx"),
                    models.Index(fields=["sales"], name="products_sales_fd66fe_idx"),
                    models.Index(fields=["shop"], name="products_shop_351aac_idx"),
                    models.Index(
                        fields=["batch_no"], name="products_batch_n_79ccc0_idx"
                    ),
                    models.Index(
                        fields=["-crawl_time"], name="products_crawl_t_3db793_idx"
                    ),
                ],
            },
        ),
    ]
