# Generated by Django 5.2.11 on 2026-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_keywords_to_crawllog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-crawl_time'], 'verbose_name': '宠物商品', 'verbose_name_plural': '宠物商品'},
        ),
        migrations.AddField(
            model_name='product',
            name='pet_type',
            field=models.CharField(blank=True, choices=[('cat', '猫咪'), ('dog', '狗狗'), ('aquatic', '水族'), ('small_pet', '小宠物'), ('other', '其他')], max_length=20, null=True, verbose_name='宠物类型'),
        ),
        migrations.AddField(
            model_name='product',
            name='pet_use',
            field=models.CharField(blank=True, choices=[('food', '食品'), ('supplies', '用品'), ('toy', '玩具'), ('healthcare', '医疗保健'), ('grooming', '清洁护理')], max_length=20, null=True, verbose_name='用途分类'),
        ),
        migrations.AlterField(
            model_name='crawllog',
            name='mode',
            field=models.CharField(help_text='normal: 标准模式, demo: 演示模式, batch: 分批采集', max_length=20, verbose_name='采集模式'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pet_type'], name='products_pet_typ_5f518c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pet_use'], name='products_pet_use_390850_idx'),
        ),
    ]
