# Generated by Django 5.2.11 on 2026-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='景点简介')),
                ('address', models.CharField(default='', max_length=200, verbose_name='地址')),
                ('category', models.CharField(choices=[('自然风光', '自然风光'), ('人文古迹', '人文古迹'), ('主题乐园', '主题乐园'), ('其他', '其他')], default='其他', max_length=20, verbose_name='类别')),
                ('region', models.CharField(default='', max_length=50, verbose_name='地区')),
                ('opening_hours', models.CharField(default='', max_length=100, verbose_name='开放时间')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='attractions/', verbose_name='封面图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='轮播图')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'attractions',
                'ordering': ['-created_at'],
            },
        ),
    ]
