# Generated by Django 5.2.11 on 2026-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='guide_count',
            field=models.IntegerField(default=0, verbose_name='攻略数量'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='level',
            field=models.CharField(blank=True, max_length=10, verbose_name='景区等级'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, verbose_name='城市排名'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='rating_percentage',
            field=models.FloatField(default=0.0, verbose_name='好评率'),
        ),
    ]
