# Generated by Django 5.2.11 on 2026-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_guide_count_attraction_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['category', 'is_deleted'], name='attractions_categor_fb455a_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['region', 'category'], name='attractions_region_3b82ae_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['view_count'], name='attractions_view_co_99fcfc_idx'),
        ),
        migrations.AddIndex(
            model_name='attraction',
            index=models.Index(fields=['is_deleted'], name='attractions_is_dele_4c3cd5_idx'),
        ),
    ]
