# Generated by Django 5.2.10 on 2026-02-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attractions", "0003_attraction_attractions_categor_fb455a_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="cover_image",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="封面图"
            ),
        ),
    ]
