# Generated by Django 5.2.11 on 2026-02-24 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_period', models.CharField(max_length=7, verbose_name='bill period')),
                ('usage', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='usage')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='amount')),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=16, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('paid_time', models.DateTimeField(blank=True, null=True, verbose_name='paid time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='devices.energytype', verbose_name='energy type')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='buildings.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'db_table': 'em_bills',
                'indexes': [models.Index(fields=['status'], name='idx_em_bills_status'), models.Index(fields=['due_date'], name='idx_em_bills_due_date')],
                'constraints': [models.UniqueConstraint(fields=('room', 'energy_type', 'bill_period'), name='uk_em_bills_room_energy_period')],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('notice_type', models.CharField(choices=[('NOTICE', 'Notice'), ('ANNOUNCEMENT', 'Announcement'), ('KNOWLEDGE', 'Knowledge')], default='NOTICE', max_length=16, verbose_name='notice type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=16, verbose_name='priority')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='publish time')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('target_role', models.CharField(choices=[('ALL', 'All'), ('ADMIN', 'Admin'), ('USER', 'User')], default='ALL', max_length=16, verbose_name='target role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('publisher', models.ForeignKey(blank=True, db_column='publisher_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_notices', to=settings.AUTH_USER_MODEL, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notices',
                'db_table': 'em_notices',
                'indexes': [models.Index(fields=['notice_type'], name='idx_em_notices_notice_type'), models.Index(fields=['publish_time'], name='idx_em_notices_publish_time'), models.Index(fields=['is_published'], name='idx_em_notices_is_published')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='action')),
                ('resource', models.CharField(max_length=128, verbose_name='resource')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='user agent')),
                ('request_method', models.CharField(blank=True, max_length=16, null=True, verbose_name='request method')),
                ('request_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='request path')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'operation log',
                'verbose_name_plural': 'operation logs',
                'db_table': 'em_operation_logs',
                'indexes': [models.Index(fields=['user'], name='idx_em_operation_logs_user_id'), models.Index(fields=['action'], name='idx_em_operation_logs_action'), models.Index(fields=['create_time'], name='idx_operation_logs_time')],
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('payment_method', models.CharField(max_length=32, verbose_name='payment method')),
                ('recharge_time', models.DateTimeField(verbose_name='recharge time')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('operator', models.ForeignKey(blank=True, db_column='operator_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_records', to=settings.AUTH_USER_MODEL, verbose_name='operator')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to='buildings.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'recharge record',
                'verbose_name_plural': 'recharge records',
                'db_table': 'em_recharge_records',
                'indexes': [models.Index(fields=['room'], name='idx_recharge_records_room'), models.Index(fields=['recharge_time'], name='idx_recharge_records_time')],
            },
        ),
    ]
