# Generated by Django 5.2.11 on 2026-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='category'),
        ),
    ]
