# Generated by Django 5.2.10 on 2026-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='食材的名称，如"鸡肉"、"土豆"等',
                        max_length=100,
                        unique=True,
                        verbose_name="食材名称",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetable", "蔬菜"),
                            ("meat", "肉类"),
                            ("seafood", "海鲜"),
                            ("seasoning", "调料"),
                            ("fruit", "水果"),
                            ("grain", "谷物"),
                            ("dairy", "乳制品"),
                            ("other", "其他"),
                        ],
                        default="other",
                        help_text="食材所属分类：蔬菜、肉类、海鲜、调料等",
                        max_length=20,
                        verbose_name="食材分类",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="食材创建的时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="食材最后更新的时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "食材",
                "verbose_name_plural": "食材",
                "db_table": "ingredients",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="ingredients_name_9f76a2_idx"),
                    models.Index(
                        fields=["category"], name="ingredients_categor_ed8c56_idx"
                    ),
                ],
            },
        ),
    ]
