# Generated by Django 5.2.10 on 2026-02-16 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="头像"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "管理员"), ("USER", "普通用户")],
                        default="USER",
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                (
                    "bind_rooms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="阶段2.3临时存储房间ID列表，阶段2.4完成后升级为ManyToMany到buildings.Room",
                        verbose_name="绑定房间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
                "db_table": "em_user_profiles",
            },
        ),
    ]
