# Generated by Django 5.2.11 on 2026-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alarm_subscriptions',
            field=models.JSONField(blank=True, default=dict, help_text='用户告警订阅偏好（如余额不足提醒、异常用能提醒）。', verbose_name='告警订阅设置'),
        ),
    ]
