# Generated by Django 5.2.11 on 2026-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_alarm_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='账户余额'),
        ),
    ]
