# Generated by Django 5.2.11 on 2026-02-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_bind_rooms',
            field=models.JSONField(blank=True, default=list, help_text='用户发起但待管理员审批的房间ID列表', verbose_name='待审核绑定申请'),
        ),
    ]
