# Generated by Django 5.2.10 on 2026-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "男"), ("FEMALE", "女")],
                        default="MALE",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系方式")),
                (
                    "id_card",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        null=True,
                        unique=True,
                        verbose_name="身份证号",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="家庭住址"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("CHEF", "厨师"),
                            ("PASTRY", "面点"),
                            ("PREP", "切配"),
                            ("CLEANER", "保洁"),
                            ("SERVER", "服务员"),
                            ("MANAGER", "经理"),
                        ],
                        max_length=20,
                        verbose_name="岗位",
                    ),
                ),
                ("entry_date", models.DateField(verbose_name="入职时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "在职"),
                            ("INACTIVE", "离职"),
                            ("LEAVE_WITHOUT_PAY", "停薪留职"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="在职状态",
                    ),
                ),
                (
                    "health_certificate_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="健康证号"
                    ),
                ),
                (
                    "health_certificate_expiry",
                    models.DateField(blank=True, null=True, verbose_name="健康证有效期"),
                ),
                (
                    "health_certificate_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="健康证图片地址"
                    ),
                ),
                (
                    "chef_certificate_level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="厨师等级证"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "员工档案",
                "verbose_name_plural": "员工档案",
                "db_table": "employee_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
