# Generated by Django 6.0.1 on 2026-02-04 07:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('category', models.CharField(choices=[('basic', '基础配置'), ('seo', 'SEO配置'), ('trade', '交易配置'), ('other', '其他配置')], db_index=True, default='other', max_length=50, verbose_name='分类')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置管理',
                'db_table': 'system_configs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(choices=[('announcement', '系统公告'), ('notification', '订单通知'), ('promotion', '促销通知'), ('system', '系统通知')], db_index=True, default='notification', max_length=20, verbose_name='消息类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('read', '已读')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息管理',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('other', '其他')], db_index=True, default='other', max_length=20, verbose_name='操作类型')),
                ('object_type', models.CharField(blank=True, default='', max_length=100, verbose_name='操作对象类型')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='操作对象ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], db_index=True, default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志管理',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
