# Generated by Django 5.2.10 on 2026-01-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="登录账号"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="登录密码")),
                (
                    "employee_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联员工档案ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "管理员"), ("EMPLOYEE", "普通员工")],
                        default="EMPLOYEE",
                        max_length=10,
                        verbose_name="角色类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ENABLED", "启用"), ("DISABLED", "禁用")],
                        default="ENABLED",
                        max_length=10,
                        verbose_name="账号状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户账号",
                "verbose_name_plural": "用户账号",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
