# Generated by Django 5.2.10 on 2026-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.IntegerField(default=5, verbose_name="迟到宽限时间（分钟）"),
                ),
                (
                    "early_leave_grace_minutes",
                    models.IntegerField(default=5, verbose_name="早退宽限时间（分钟）"),
                ),
                (
                    "late_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=10,
                        verbose_name="迟到扣款（元/次）",
                    ),
                ),
                (
                    "missing_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=10,
                        verbose_name="缺卡扣款（元/次）",
                    ),
                ),
                (
                    "days_per_month",
                    models.DecimalField(
                        decimal_places=2,
                        default=21.75,
                        max_digits=5,
                        verbose_name="月计薪天数",
                    ),
                ),
                (
                    "hours_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=5,
                        verbose_name="日工作小时数",
                    ),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="加班工资倍率",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "db_table": "system_settings",
            },
        ),
    ]
