# Generated by Django 5.2.11 on 2026-02-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_flexible_clock_in',
            field=models.BooleanField(default=True, help_text='无排班时是否允许签到', verbose_name='允许弹性签到'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_multiple_attendance',
            field=models.BooleanField(default=True, help_text='同一天是否允许多次签到签退（如早班+晚班）', verbose_name='允许多次签到'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='clock_in_advance_minutes',
            field=models.IntegerField(default=30, help_text='允许在班次开始前多少分钟内签到', verbose_name='签到提前缓冲时间（分钟）'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='clock_out_delay_minutes',
            field=models.IntegerField(default=30, help_text='允许在班次结束后多少分钟内签退', verbose_name='签退延后缓冲时间（分钟）'),
        ),
    ]
