# Generated by Django 6.0.1 on 2026-02-04 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('category', models.CharField(choices=[('order', '订单问题'), ('payment', '支付问题'), ('shipping', '物流问题'), ('product', '商品问题'), ('return', '退换货问题'), ('account', '账户问题'), ('other', '其他问题')], db_index=True, default='other', max_length=20, verbose_name='分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题管理',
                'db_table': 'faqs',
                'ordering': ['category', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModificationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_image', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片URL')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='作者')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '改装案例',
                'verbose_name_plural': '改装案例管理',
                'db_table': 'modification_cases',
                'ordering': ['-sort_order', '-published_at', '-created_at'],
            },
        ),
    ]
