# Generated by Django 5.2 on 2026-02-25 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{2,3}$')])),
                ('country_name', models.CharField(max_length=128, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('continent', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'regions',
                'ordering': ['country_name'],
                'indexes': [models.Index(fields=['country_code'], name='region_code_idx'), models.Index(fields=['country_name'], name='region_name_idx')],
            },
        ),
    ]
