# Generated by Django 5.2.11 on 2026-02-28 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='公告ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('priority', models.IntegerField(choices=[(1, '普通'), (2, '重要'), (3, '紧急')], default=1, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-priority', '-published_at'],
                'indexes': [models.Index(fields=['status'], name='announcemen_status_a07d93_idx'), models.Index(fields=['priority'], name='announcemen_priorit_370592_idx'), models.Index(fields=['-is_pinned'], name='announcemen_is_pinn_8a8581_idx'), models.Index(fields=['-published_at'], name='announcemen_publish_4a0d1e_idx')],
            },
        ),
    ]
