# Generated by Django 5.2.11 on 2026-02-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('CAMPUS', 'Campus'), ('BUILDING', 'Building'), ('METER', 'Meter')], max_length=16, verbose_name='target type')),
                ('target_id', models.CharField(max_length=64, verbose_name='target id')),
                ('forecast_date', models.DateField(verbose_name='forecast date')),
                ('forecast_value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='forecast value')),
                ('horizon_days', models.PositiveIntegerField(default=7, verbose_name='horizon days')),
                ('model_version', models.CharField(default='linear-v1', max_length=64, verbose_name='model version')),
                ('room_id', models.BigIntegerField(blank=True, null=True, verbose_name='room id')),
                ('department', models.CharField(blank=True, max_length=128, null=True, verbose_name='department')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='buildings.building', verbose_name='building')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='buildings.campus', verbose_name='campus')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='devices.energytype', verbose_name='energy type')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='devices.device', verbose_name='meter')),
            ],
            options={
                'verbose_name': 'energy forecast',
                'verbose_name_plural': 'energy forecasts',
                'db_table': 'em_energy_forecasts',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_forecast_target'), models.Index(fields=['forecast_date'], name='idx_forecast_date'), models.Index(fields=['energy_type'], name='idx_forecast_energy_type'), models.Index(fields=['campus'], name='idx_forecast_campus'), models.Index(fields=['building'], name='idx_forecast_building'), models.Index(fields=['meter'], name='idx_forecast_meter')],
                'constraints': [models.UniqueConstraint(fields=('target_type', 'target_id', 'energy_type', 'forecast_date', 'horizon_days'), name='uk_em_energy_forecast_target_type_id_date')],
            },
        ),
    ]
