# Generated by Django 5.2.11 on 2026-02-25 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='achievement code')),
                ('name', models.CharField(max_length=128, verbose_name='achievement name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='icon')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='points')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'db_table': 'em_achievements',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='idx_achievement_active_sort')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False, verbose_name='unlocked')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='progress')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='unlocked at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='analysis.achievement', verbose_name='achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user achievement',
                'verbose_name_plural': 'user achievements',
                'db_table': 'em_user_achievements',
                'indexes': [models.Index(fields=['user', 'unlocked'], name='idx_user_achv_user_unlock')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='uk_user_achv_user_achv')],
            },
        ),
    ]
