# Generated by Django 5.2.11 on 2026-02-24 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='rule name')),
                ('condition_type', models.CharField(choices=[('THRESHOLD', 'Threshold'), ('MUTATION', 'Mutation')], max_length=16, verbose_name='condition type')),
                ('threshold_value', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='threshold value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_rules', to='devices.energytype', verbose_name='energy type')),
            ],
            options={
                'verbose_name': 'alarm rule',
                'verbose_name_plural': 'alarm rules',
                'db_table': 'em_alarm_rules',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('THRESHOLD', 'Threshold'), ('MUTATION', 'Mutation'), ('OFFLINE', 'Offline')], max_length=16, verbose_name='alarm type')),
                ('alarm_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='alarm value')),
                ('alarm_time', models.DateTimeField(verbose_name='alarm time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored')], default='PENDING', max_length=16, verbose_name='status')),
                ('handle_time', models.DateTimeField(blank=True, null=True, verbose_name='handle time')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='devices.device', verbose_name='device')),
                ('handler', models.ForeignKey(blank=True, db_column='handler_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alarms', to=settings.AUTH_USER_MODEL, verbose_name='handler')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='alarms.alarmrule', verbose_name='alarm rule')),
            ],
            options={
                'verbose_name': 'alarm',
                'verbose_name_plural': 'alarms',
                'db_table': 'em_alarms',
            },
        ),
        migrations.AddIndex(
            model_name='alarmrule',
            index=models.Index(fields=['energy_type'], name='idx_alarm_rules_energy_type'),
        ),
        migrations.AddIndex(
            model_name='alarmrule',
            index=models.Index(fields=['is_active'], name='idx_em_alarm_rules_is_active'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['device'], name='idx_em_alarms_device_id'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['rule'], name='idx_em_alarms_rule_id'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['alarm_time'], name='idx_em_alarms_alarm_time'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status'], name='idx_em_alarms_status'),
        ),
    ]
