# Generated by Django 5.2.10 on 2026-01-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_period",
                    models.CharField(
                        help_text="评估周期 (如: 2025-Q1, 2025-01)", max_length=20
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="评分 (1-5分)",
                        max_digits=2,
                        null=True,
                    ),
                ),
                ("strengths", models.TextField(blank=True, default="", help_text="优点")),
                (
                    "improvements",
                    models.TextField(blank=True, default="", help_text="改进建议"),
                ),
                ("goals", models.TextField(blank=True, default="", help_text="设定目标")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        help_text="状态",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["hr", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "绩效评估",
                "verbose_name_plural": "绩效评估",
                "ordering": ["-created_at"],
                "unique_together": {("employee", "review_period")},
            },
        ),
    ]
