# Generated by Django 5.2.10 on 2026-01-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="模板名称", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="模板描述"),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否启用")),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text='考核项列表 [{"name": "工作质量", "weight": 30, "desc": "完成任务的质量"}]',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "绩效模板",
                "verbose_name_plural": "绩效模板",
                "ordering": ["-created_at"],
            },
        ),
    ]
