# Generated by Django 5.2 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('level', models.CharField(choices=[('national', 'National'), ('provincial', 'Provincial'), ('city_county', 'City/County')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='category_name_idx'), models.Index(fields=['code'], name='category_code_idx')],
            },
        ),
    ]
