# Generated by Django 5.2 on 2026-02-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heritage', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=16)),
                ('level', models.CharField(blank=True, choices=[('national', 'National'), ('provincial', 'Provincial'), ('city_county', 'City/County')], db_index=True, default='', max_length=32)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heritage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inheritors', to='heritage.heritageitem')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inheritors', to='regions.region')),
            ],
            options={
                'db_table': 'inheritors',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['name'], name='inheritor_name_idx'), models.Index(fields=['heritage_item'], name='inheritor_heritage_idx')],
                'constraints': [models.UniqueConstraint(fields=('heritage_item', 'name'), name='uniq_inheritor_name_per_heritage')],
            },
        ),
    ]
