# Generated by Django 6.0.1 on 2026-01-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', '病假'), ('PERSONAL', '事假'), ('COMPENSATORY', '调休')], max_length=20, verbose_name='请假类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=20, verbose_name='审批状态')),
                ('approval_remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employeeprofile', verbose_name='审批人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employeeprofile', verbose_name='员工')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'leaves_leave_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee'], name='leaves_leav_employe_ddca43_idx'), models.Index(fields=['status'], name='leaves_leav_status_645df1_idx'), models.Index(fields=['created_at'], name='leaves_leav_created_be1acd_idx'), models.Index(fields=['start_time'], name='leaves_leav_start_t_865e70_idx')],
            },
        ),
    ]
