# Generated by Django 5.2.11 on 2026-02-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', '年假'), ('SICK', '病假'), ('PERSONAL', '事假'), ('MATERNITY', '产假'), ('PATERNITY', '陪产假'), ('COMPENSATORY', '调休'), ('OTHER', '其他')], max_length=20, verbose_name='请假类型'),
        ),
    ]
