# Generated by Django 5.2.10 on 2026-02-15 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProtectionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=100)),
                (
                    "min_aqi",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                (
                    "max_aqi",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                (
                    "population_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "GENERAL"),
                            ("CHILDREN", "CHILDREN"),
                            ("ELDERLY", "ELDERLY"),
                            ("PATIENTS", "PATIENTS"),
                            ("SENSITIVE", "SENSITIVE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("advice", models.TextField()),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["population_type", "min_aqi", "max_aqi"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("min_aqi__lte", models.F("max_aqi"))),
                        name="ck_rule_min_le_max",
                    )
                ],
            },
        ),
    ]
