# Generated by Django 5.2.10 on 2026-01-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="岗位名称")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="岗位编码"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="岗位描述"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
