# Generated by Django 5.2.10 on 2026-01-26 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_post"),
    ]

    operations = []
