# Generated by Django 6.0.1 on 2026-01-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_add_department_to_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['department__sort_order', 'department_id', 'sort_order', 'id'], 'verbose_name': '岗位', 'verbose_name_plural': '岗位'},
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='organization.department', verbose_name='所属部门'),
            preserve_default=False,
        ),
    ]
