# Generated by Django 5.2.10 on 2026-02-07 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="历史记录ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="历史价格（元）"
                    ),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="历史销量")),
                ("record_date", models.DateField(verbose_name="记录日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品历史价格",
                "verbose_name_plural": "商品历史价格",
                "db_table": "price_history",
                "ordering": ["-record_date"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="price_histo_product_68985b_idx"
                    ),
                    models.Index(
                        fields=["-record_date"], name="price_histo_record__30f3d2_idx"
                    ),
                    models.Index(
                        fields=["product", "-record_date"],
                        name="price_histo_product_3f051a_idx",
                    ),
                ],
                "unique_together": {("product", "record_date")},
            },
        ),
    ]
