# Generated by Django 5.2.10 on 2026-02-08 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_pricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_desc",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="价格描述"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="价格单位"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_attributes",
            field=models.JSONField(blank=True, null=True, verbose_name="商品属性"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="天猫商品ID"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="地区"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_nick",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="卖家昵称"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shop_tags",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="店铺标签"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="商品标签"
            ),
        ),
        migrations.AlterField(
            model_name="crawllog",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtop_api", "淘宝 mtop API"),
                    ("real_api", "真实API (g_page_config)"),
                    ("json", "旧版JSON API"),
                    ("playwright", "Playwright渲染"),
                    ("demo", "演示模式"),
                ],
                max_length=20,
                null=True,
                verbose_name="采集来源",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="batch_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="采集批次号"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_id"], name="products_product_c3fbc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_brand_b2547a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_fce6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["region"], name="products_region_f91092_idx"),
        ),
    ]
