# Generated by Django 5.2.10 on 2026-01-29 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recipes", "0002_recipeingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="用户收藏该菜谱的时间",
                        verbose_name="收藏时间",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="被收藏的菜谱",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="recipes.recipe",
                        verbose_name="菜谱",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="收藏该菜谱的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户收藏",
                "verbose_name_plural": "用户收藏",
                "db_table": "user_favorites",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_favori_user_id_216ac3_idx"
                    ),
                    models.Index(
                        fields=["recipe"], name="user_favori_recipe__6f6610_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="user_favori_created_d0b934_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe"), name="unique_user_recipe_favorite"
                    )
                ],
            },
        ),
    ]
