# Generated by Django 5.2.10 on 2026-01-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='菜谱的名称，如"宫保鸡丁"', max_length=200, verbose_name="菜谱名称"
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True,
                        help_text='所属菜系，如"川菜"、"粤菜"等',
                        max_length=50,
                        verbose_name="菜系分类",
                    ),
                ),
                (
                    "scene_type",
                    models.CharField(
                        blank=True,
                        help_text='适用场景，如"早餐"、"午餐"、"晚餐"等',
                        max_length=50,
                        verbose_name="场景分类",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text='适用人群，如"儿童"、"老人"、"孕妇"等',
                        max_length=100,
                        verbose_name="适用人群",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                        default="medium",
                        help_text="烹饪难度等级：简单、中等、困难",
                        max_length=10,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        blank=True,
                        help_text="完成这道菜所需的时间，单位为分钟",
                        null=True,
                        verbose_name="烹饪时长（分钟）",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="菜谱成品图的URL地址",
                        max_length=500,
                        verbose_name="成品图片URL",
                    ),
                ),
                (
                    "steps",
                    models.TextField(
                        blank=True,
                        help_text="菜谱的详细制作步骤，可使用JSON格式存储结构化数据",
                        verbose_name="制作步骤",
                    ),
                ),
                (
                    "flavor_tags",
                    models.CharField(
                        blank=True,
                        help_text='口味标签，多个标签用逗号分隔，如"辣,甜,酸"',
                        max_length=200,
                        verbose_name="口味标签",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0, help_text="菜谱被点击浏览的次数", verbose_name="点击量"
                    ),
                ),
                (
                    "favorite_count",
                    models.IntegerField(
                        default=0, help_text="菜谱被收藏的次数", verbose_name="收藏量"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="菜谱创建的时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="菜谱最后更新的时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱",
                "verbose_name_plural": "菜谱",
                "db_table": "recipes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="recipes_name_66b98f_idx"),
                    models.Index(
                        fields=["cuisine_type"], name="recipes_cuisine_3862f6_idx"
                    ),
                    models.Index(
                        fields=["difficulty"], name="recipes_difficu_9b84bb_idx"
                    ),
                    models.Index(
                        fields=["scene_type"], name="recipes_scene_t_695d9f_idx"
                    ),
                    models.Index(
                        fields=["view_count"], name="recipes_view_co_7980ec_idx"
                    ),
                    models.Index(
                        fields=["favorite_count"], name="recipes_favorit_456657_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="recipes_created_00c815_idx"
                    ),
                ],
            },
        ),
    ]
