# Generated by Django 5.2.10 on 2026-01-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        help_text='食材用量，如"200g"、"2个"、"适量"等',
                        max_length=100,
                        verbose_name="用量描述",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="食材在菜谱中的显示顺序", verbose_name="排序序号"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        help_text="关联的食材",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="ingredients.ingredient",
                        verbose_name="食材",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="关联的菜谱",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                        verbose_name="菜谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱食材关联",
                "verbose_name_plural": "菜谱食材关联",
                "db_table": "recipe_ingredients",
                "ordering": ["recipe", "sort_order"],
                "indexes": [
                    models.Index(
                        fields=["recipe"], name="recipe_ingr_recipe__c09862_idx"
                    ),
                    models.Index(
                        fields=["ingredient"], name="recipe_ingr_ingredi_1f18f7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
                    )
                ],
            },
        ),
    ]
