# Generated by Django 5.2.10 on 2026-01-25 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("phone", "手机号"),
                            ("email", "邮箱"),
                            ("emergency_contact", "紧急联系人"),
                        ],
                        max_length=20,
                        verbose_name="修改类型",
                    ),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, max_length=255, verbose_name="原值"),
                ),
                ("new_value", models.CharField(max_length=255, verbose_name="新值")),
                ("reason", models.TextField(blank=True, verbose_name="修改原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已驳回"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("reviewer_comment", models.TextField(blank=True, verbose_name="审批意见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="审批时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "信息修改申请",
                "verbose_name_plural": "信息修改申请",
                "db_table": "accounts_usereditrequest",
                "ordering": ["-created_at"],
            },
        ),
    ]
