# Generated by Django 5.2.10 on 2026-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usereditrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee", "普通员工"),
                            ("hr", "人事专员"),
                            ("admin", "管理员"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="角色",
                    ),
                ),
                (
                    "menu_permissions",
                    models.JSONField(
                        default=list, help_text="可访问的菜单路由列表", verbose_name="菜单权限"
                    ),
                ),
                (
                    "button_permissions",
                    models.JSONField(
                        default=list, help_text="可显示的操作按钮列表", verbose_name="按钮权限"
                    ),
                ),
                (
                    "data_permission",
                    models.CharField(
                        choices=[
                            ("all", "全部数据"),
                            ("department", "本部门数据"),
                            ("self", "仅本人"),
                        ],
                        default="self",
                        help_text="可访问的数据范围",
                        max_length=20,
                        verbose_name="数据权限",
                    ),
                ),
                (
                    "attendance_permission",
                    models.CharField(
                        choices=[
                            ("all", "全部数据"),
                            ("department", "本部门数据"),
                            ("self", "仅本人"),
                        ],
                        default="self",
                        max_length=20,
                        verbose_name="考勤数据权限",
                    ),
                ),
                (
                    "salary_permission",
                    models.CharField(
                        choices=[
                            ("all", "全部数据"),
                            ("department", "本部门数据"),
                            ("self", "仅本人"),
                        ],
                        default="self",
                        max_length=20,
                        verbose_name="薪资数据权限",
                    ),
                ),
                (
                    "can_access_datacenter",
                    models.BooleanField(default=False, verbose_name="可访问数据中心"),
                ),
                (
                    "can_access_performance",
                    models.BooleanField(default=False, verbose_name="可访问绩效管理"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色权限配置",
                "verbose_name_plural": "角色权限配置",
                "db_table": "accounts_rolepermission",
            },
        ),
    ]
