# Generated by Django 5.2.10 on 2026-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rolepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "require_registration_approval",
                    models.BooleanField(
                        default=False,
                        help_text="新用户注册后是否需要管理员审批才能登录",
                        verbose_name="注册需审批",
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=6, help_text="密码最小长度要求", verbose_name="密码最小长度"
                    ),
                ),
                (
                    "password_require_uppercase",
                    models.BooleanField(
                        default=False, help_text="密码是否需要包含大写字母", verbose_name="需要大写字母"
                    ),
                ),
                (
                    "password_require_lowercase",
                    models.BooleanField(
                        default=True, help_text="密码是否需要包含小写字母", verbose_name="需要小写字母"
                    ),
                ),
                (
                    "password_require_number",
                    models.BooleanField(
                        default=True, help_text="密码是否需要包含数字", verbose_name="需要数字"
                    ),
                ),
                (
                    "password_require_special",
                    models.BooleanField(
                        default=False, help_text="密码是否需要包含特殊字符", verbose_name="需要特殊字符"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5, help_text="连续登录失败后锁定账户的次数", verbose_name="最大登录尝试次数"
                    ),
                ),
                (
                    "login_lockout_duration",
                    models.PositiveIntegerField(
                        default=30, help_text="账户锁定时间（分钟）", verbose_name="锁定时间(分钟)"
                    ),
                ),
                (
                    "session_timeout",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="用户无操作后会话超时时间（分钟）",
                        verbose_name="会话超时(分钟)",
                    ),
                ),
                (
                    "allow_multiple_sessions",
                    models.BooleanField(
                        default=True,
                        help_text="是否允许同一账户在多个设备同时登录",
                        verbose_name="允许多端登录",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "accounts_systemconfig",
            },
        ),
    ]
