# Generated by Django 6.0.1 on 2026-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='usereditrequest',
            name='edit_type',
            field=models.CharField(choices=[('phone', '手机号'), ('email', '邮箱'), ('emergency_contact', '紧急联系人'), ('address', '通讯地址'), ('id_card', '身份证号')], max_length=20, verbose_name='修改类型'),
        ),
    ]
