# Generated by Django 6.0.1 on 2026-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_user_emergency_contact_user_id_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='password_storage_mode',
            field=models.CharField(choices=[('plain', '明文'), ('encrypted', '密文')], default='encrypted', help_text='明文模式下密码将不经加密直接存储，密文模式下使用哈希加密', max_length=10, verbose_name='密码存储模式'),
        ),
    ]
